apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: tvk-preflight
spec:
  homepage: https://github.com/trilioData/tvk-plugins/blob/main/docs/preflight/README.md
  shortDescription: TVK application preflight check for k8s cluster
  version: PREFLIGHT_VERSION
  caveats: |
    Curl and Git neeed to be installed on system for Krew index update to work properly
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/trilioData/tvk-plugins/releases/download/PREFLIGHT_VERSION/preflight.tar.gz
    sha256: PREFLIGHT_TAR_CHECKSUM
    bin: preflight
    files:
    - from: preflight/preflight
      to: .

  description: |
    tvk-preflight is a kubectl plugin which checks whether all the pre-requisites are met before installing Triliovault
    for Kubernetes(TVK) application in a Kubernetes cluster.

    > Check available flags for preflight plugin with :-
    kubectl preflight --help

    --storageclass - Name of storage class being used in k8s cluster (Needed)
    --snapshotclass - Name of volume snapshot class being used in k8s cluster (Needed)
    --kubeconfig - Kubeconfig path, if not given default is used by kubectl (Optional)

    > Usage :-

    kubectl tvk-preflight --storageclass my-hostpath-sc --snapshotclass default-snapclass --kubeconfig /home/usr/kubeconfig
