apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: tvk-target-browser
spec:
  homepage: https://github.com/trilioData/tvk-plugins/blob/master/docs/target-browser/README.md
  shortDescription: TVK Target Browser queries mounted target to get details of backup, backupPlan, backup metadata, etc.
  version: TARGET_BROWSER_VERSION
  caveats: |
    Curl and Git neeed to be installed on system for Krew index update to work properly
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/TARGET_BROWSER_VERSION/target-browser_TARGET_BROWSER_VERSION_linux_amd64.tar.gz
    sha256: TARGET_BROWSER_LINUX_TAR_CHECKSUM
    bin: target-browser
    files:
    - from: '*'
      to: .

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/TARGET_BROWSER_VERSION/target-browser_TARGET_BROWSER_VERSION_darwin_amd64.tar.gz
    sha256: TARGET_BROWSER_DARWIN_TAR_CHECKSUM
    bin: target-browser
    files:
    - from: '*'
      to: .

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/TARGET_BROWSER_VERSION/target-browser_TARGET_BROWSER_VERSION_windows_amd64.zip
    sha256: TARGET_BROWSER_WINDOWS_TAR_CHECKSUM
    bin: target-browser.exe
    files:
    - from: '*'
      to: .

  description: |
    tvk-target-browser is a kubectl plugin which can query content of mounted target location to get details of backup,
    backupPlan and metadata details of backup via HTTP/HTTPS calls to target-browser server.

    > Check available commands, flags & options for tvk-target-browser plugin with :-
    kubectl tvk-target-browser --help

    > Usage :-

    # List of backupPlans
    kubectl tvk-target-browser get backupPlan --target-name <name> --target-namespace <namespace>

    # List of backups
    kubectl tvk-target-browser get backup --target-name <name> --target-namespace <namespace>

    # List of backups using backupPlan UID
    kubectl tvk-target-browser get backup --backup-plan-uid <uid> --target-name <name> --target-namespace <namespace>

    # Get specific backupPlan
    kubectl tvk-target-browser get backupPlan <backup-plan-uid>  --target-name <name> --target-namespace <namespace>

    # Get specific backup
    kubectl tvk-target-browser get backup <backup-uid> --target-name <name> --target-namespace <namespace>

    # Metadata of specific backup object
    kubectl tvk-target-browser get metadata --backup-uid <uid> --backup-plan-uid <uid> --target-name <name> --target-namespace <namespace>

    # Resource Metadata of specific backup object
    kubectl tvk-target-browser get resource-metadata --backup-uid <uid> --backup-plan-uid <uid> --target-name <name> --target-namespace <namespace> --group <group> --version <version> --kind <kind> --name <resource-name>

    # Trilio Resources for specific backup object
    kubectl tvk-target-browser get backup trilio-resources <backup-uid> --backup-plan-uid <uid> --kinds ClusterBackupPlan,Backup,Hook --target-name <name> --target-namespace <namespace>

    # List of backups: filter by [expirationStartTime] and [expirationEndTime]
    kubectl tvk-target-browser get backup --expiration-start-time <expiration-start-time> --expiration-end-time <expiration-end-time>--target-name <name> --target-namespace <namespace>

    # List of backups: filter by [creationStartTime] and [creationEndTime]
    kubectl tvk-target-browser get backup --creation-start-time <creation-start-time> --creation-end-time <creation-end-time>--target-name <name> --target-namespace <namespace>

    # List of backupPlans: filter by [creationStartTime] and [creationEndTime]
    kubectl tvk-target-browser get backupPlan --creation-start-time <creation-start-time> --creation-end-time <creation-end-time>--target-name <name> --target-namespace <namespace>
