apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: tvk-log-collector
spec:
  homepage: https://github.com/trilioData/tvk-plugins/blob/master/docs/log-collector/README.md
  shortDescription: TVK Log-Collector to collect logs of TVK Resources
  version: LOG_COLLECTOR_VERSION
  caveats: |
    Curl and Git neeed to be installed on system for Krew index update to work properly
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_linux_amd64.tar.gz
    sha256: LOG_COLLECTOR_LINUX_AMD64_TAR_CHECKSUM
    bin: log-collector
    files:
    - from: '*'
      to: .

  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_linux_arm64.tar.gz
    sha256: LOG_COLLECTOR_LINUX_ARM64_TAR_CHECKSUM
    bin: log-collector
    files:
    - from: '*'
      to: .
  - selector:
      matchLabels:
        os: linux
        arch: arm
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_linux_arm.tar.gz
    sha256: LOG_COLLECTOR_LINUX_ARM_TAR_CHECKSUM
    bin: log-collector
    files:
    - from: '*'
      to: .

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_darwin_amd64.tar.gz
    sha256: LOG_COLLECTOR_DARWIN_AMD64_TAR_CHECKSUM
    bin: log-collector
    files:
    - from: '*'
      to: .
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_darwin_arm64.tar.gz
    sha256: LOG_COLLECTOR_DARWIN_ARM64_TAR_CHECKSUM
    bin: log-collector
    files:
    - from: '*'
      to: .

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_windows_amd64.zip
    sha256: LOG_COLLECTOR_WINDOWS_AMD64_TAR_CHECKSUM
    bin: log-collector.exe
    files:
    - from: '*'
      to: .
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_windows_arm64.zip
    sha256: LOG_COLLECTOR_WINDOWS_ARM64_TAR_CHECKSUM
    bin: log-collector.exe
    files:
    - from: '*'
      to: .
  - selector:
      matchLabels:
        os: windows
        arch: arm
    uri: https://github.com/trilioData/tvk-plugins/releases/download/LOG_COLLECTOR_VERSION/log-collector_LOG_COLLECTOR_VERSION_windows_arm.zip
    sha256: LOG_COLLECTOR_WINDOWS_ARM_TAR_CHECKSUM
    bin: log-collector.exe
    files:
    - from: '*'
      to: .

  description: |
    tvk-log-collector is a kubectl plugin which collects the information mainly yaml configuration and logs from k8s cluster for
    debugging TVK application.

    This plugin will generate triliovault-<date-time>.zip file containing cluster debugging information.

    > Check available flags for tvk-log-collector plugin with :-
    kubectl tvk-log-collector --help

    Parameter   	Default     	Description
    --clustered 	false       	whether clustered installtion of trilio application
    --namespaces 	[]          	list of namespaces to look for resources
    --kube_config 	~/.kube/config 	path to the kubernetes config
    --keep-source-folder 	    false 	        Keep source directory and Zip both
    --log-level 	INFO 	        log level for debugging

    > Usage :-

    kubectl tvk-log-collector --clustered --log-level INFO --kubeconfig /home/usr/kubeconfig
