name: golangci-lint
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.go'
permissions:
    contents: read
    pull-requests: write
# Optional: allow read access to pull request. Use with `only-new-issues` option.
# pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.8
      - uses: actions/checkout@v4
      - name: golangci-lint
        id: lint
        uses: golangci/golangci-lint-action@v7
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v2.6.2

          # Keep lint execution rooted at the checked out repository.
          working-directory: .

          # Optional: golangci-lint command line arguments.
          args: --verbose --config=./.golangci.yaml ./...

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf  # v1
        if: failure()
        with:
          labels: do-not-merge/hold
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0  # v1
        if: success()
        with:
          labels: do-not-merge/hold