# CI WorkFlow for testing Plugin Manifests
name: Plugin Manifests CI
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'plugins/**'
      - 'hack/validate-plugin-manifests.sh'
      - 'hack/install-required-utilities.sh'
      - '.github/workflows/plugin-manifests.yml'

permissions:
  contents: read

jobs:
  # validate-plugin-manifests job validates plugin manifests which are under 'plugins' dir
  # (Checks structural schema, version semantics, install & uninstall of plugins using plugin manifests yaml)
  validate-plugin-manifests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2

    - name: Run yaml lint
      uses: reviewdog/action-yamllint@b1a8e58c959b83e9efa14a721d209bc2ba34b9d6  # v1
      with:
        fail_level: error
        reporter: local
        filter_mode: nofilter

    - name: Setup Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4  # v4
      with:
        go-version: '1.24'

    - name: Ensure Required Utilities Installed
      run: make install-required-utilities

    - name: Validate Updated Plugin Manifests
      run: make validate-plugin-manifests
